services:
  - type: web
    name: news-break-ads-crawler-v1-3
    runtime: docker
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ENABLE_FILE_LOGGING
        value: false
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    autoDeploy: true
    disk:
      name: data-storage
      mountPath: /opt/render/project/src/data
      sizeGB: 2