services:
  - type: web
    name: newsbreak-ads-crawler
    runtime: docker
    repo: https://github.com/YOUR-GITHUB-USERNAME/news-break-ads-crawler
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    buildCommand: npm install --only=production
    startCommand: node app.js