services:
  - type: web
    name: news-break-ads-crawler
    runtime: docker
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ENABLE_FILE_LOGGING
        value: false
    autoDeploy: false